Expanded on SCION-IP Gateway
scionassociation/scion-dp_I-D pull request #68
Opened 2024-10-04 10:46 UTC by knmeynell

2024-10-04 17:17 UTC, nicorusti requested changes
I made a few changes: 

- step by step description of steps involved when forwarding traffic between two SIGs (based on https://docs.anapaya.net/en/latest/edge/configuration/scion-tunneling/#overview) 
- Fixing figures
- Added some TODOs

- [ ] @oncilla we felt we had to add more to address Harald and Eliot's concerns. Can you have an overall look at this section, and let us know if this is ok?
- [ ] @jiceatscion can you help clarifying the frame fields? (e.g. correctness of field lengths, descriptions)
- [ ] How are some fields set? How about sessions?
- [ ] Also, shall we move the SIG section before security considerations? I think that section is always at the end

2024-10-07 08:45 UTC, jiceatscion commented on draft-dekater-scion-dataplane.md
> +The SCION IP Gateway (SIG) enables IP packets to be tunnelled over SCION to support communication between hosts that do not run a SCION implementation. A SIG acts as a router from the perspective of
"at the edge an enterprise network" -> "at the edge of an enterprise network"

2024-10-07 08:47 UTC, jiceatscion commented on draft-dekater-scion-dataplane.md
> +3. Based on the destination IP address, the source SIG determines the destination SIG's ISD-AS, endpoint address. To achieve this, SIGs may be pre-configured with static IP prefix to remote SIG SCION
"with the corresponding remote SIG" -> "with other SIGs". There cannot be a *corresponding* remote SIG until it has been found by way of said dynamic routing protocol or configuration (the latter removing the need to speak for that purpose).

2024-10-07 08:52 UTC, jiceatscion commented on draft-dekater-scion-dataplane.md
> +A pair of SIGs establishes a SIG tunneling session. TODO: how?.  Within each session there may be multiple streams which is useful to distinguish between traffic sent by different SIG instances. For
"distinguish between traffic sent by different SIG instances" -> does this mean "different SIG /incarnations/ ?"... that's what the following example seems to imply.

2024-10-07 08:53 UTC, jiceatscion commented on draft-dekater-scion-dataplane.md
> +Each SIG frame has a sequence number is used by the egress SIG to reassemble the encapsulated IP packets within a stream.
"has a sequence number is used" -> "has a sequence number that is used"

2024-10-07 08:56 UTC, jiceatscion commented on draft-dekater-scion-dataplane.md
> +- how is the session established and teared down?
Me no speak English good, but... "established and teared down?": isn't that supposed to be "established and torn down"?

2024-10-07 09:03 UTC, knmeynell commented on draft-dekater-scion-dataplane.md
> +The SCION IP Gateway (SIG) enables IP packets to be tunnelled over SCION to support communication between hosts that do not run a SCION implementation. A SIG acts as a router from the perspective of
Okay

2024-10-07 09:03 UTC, knmeynell commented on draft-dekater-scion-dataplane.md
> +Each SIG frame has a sequence number is used by the egress SIG to reassemble the encapsulated IP packets within a stream.
Okay

2024-10-07 09:04 UTC, knmeynell commented on draft-dekater-scion-dataplane.md
> +- how is the session established and teared down?
'established and torn down' would be correct.

2024-10-07 09:11 UTC, jiceatscion commented on draft-dekater-scion-dataplane.md
> +- `Index` (16 bits) is the byte offset of the first beginning of an IP packet within the payload. If no IP packet starts in the payload, e.g. if the frame contains only a trailing part of an IP packe
"if the frame contains only a trailing part of an IP packet": I think it would be more accurate to say "if the frame contains only the middle part of an IP packet". It is more likely than the trailing part, so a more relevant example". The case where it is the trailing part is a corner case; the packet would have to end exactly where the frame ends for there to be no beginning of packet there. That must happen a bit more often than chance alone, due to the fact that we can't fit a fragment shorter than 20 bytes at the end of a frame, but still a minority case, I think.

2024-10-07 09:14 UTC, jiceatscion commented on draft-dekater-scion-dataplane.md
> +A pair of SIGs establishes a SIG tunneling session. TODO: how?.  Within each session there may be multiple streams which is useful to distinguish between traffic sent by different SIG instances. For
I admit that I do not know exactly when/why new sessions are established. It is probably an important and not part of the wire format part of the protocol (so-called choreography) for inter-SIG compatibility. Should we attempt at describing it. I can research it in the code.

2024-10-07 09:32 UTC, jiceatscion commented on draft-dekater-scion-dataplane.md
> +- `Sequence Number` (64 bits) indicates the position of the frame within a stream. Consecutive frames can be used to reassemble IP packets split among multiple frames.
Should we say what happens if a frame goes missing/re-ordered and the sequence cannot be re-assembled? The code we have in the OS impl is pretty rustic. It makes the optimistic assumption that this rarely happens and discards everything in its buffer when a gap appears (i.e. when a frame arrives that is not the next one in sequence). So just like IP fragmentation: fragment re-ordering is the death of the packet.

2024-10-07 09:49 UTC, jiceatscion reviewed
Made some suggestions.

2024-10-08 14:24 UTC, nicorusti commented on draft-dekater-scion-dataplane.md
> +A pair of SIGs establishes a SIG tunneling session. TODO: how?.  Within each session there may be multiple streams which is useful to distinguish between traffic sent by different SIG instances. For
Yes, can you find something more about how these sessions are established?

2024-10-08 14:25 UTC, nicorusti commented on draft-dekater-scion-dataplane.md
> +Each SIG frame has a sequence number is used by the egress SIG to reassemble the encapsulated IP packets within a stream.
@knmeynell I did not see this change in the text,  committed it now.

2024-10-08 14:26 UTC, nicorusti commented on draft-dekater-scion-dataplane.md
> +- how is the session established and teared down?
Thanks for catching i. It is a TODO anyways, where can we find something more  about this?

2024-10-08 14:28 UTC, nicorusti commented on draft-dekater-scion-dataplane.md
> +- `Index` (16 bits) is the byte offset of the first beginning of an IP packet within the payload. If no IP packet starts in the payload, e.g. if the frame contains only a trailing part of an IP packe
How about: 
> e.g. if the frame contains only the middle or trailing part of an IP packet

2024-10-08 14:36 UTC, nicorusti commented on draft-dekater-scion-dataplane.md
> +- `Stream` (20 bits), along with the session, it identifies a unique sequence of SIG frames. Frames from the same stream are, on the remote SIG, put into the same reassembly queue. There may be multi
Is this set randomly or not?  Here comment says random, but in practice it is an increasing number
https://github.com/scionproto/scion/blob/aa917bb458d6675efc55b4a23fda2c694094553e/gateway/dataplane/encoder.go#L196

2024-10-08 14:41 UTC, nicorusti commented on draft-dekater-scion-dataplane.md
> +- `Sequence Number` (64 bits) indicates the position of the frame within a stream. Consecutive frames can be used to reassemble IP packets split among multiple frames.
absolutely, maybe this can be a couple of sentences about fragmentation? 
I'm not sure if we can write about a potentially better approach?

2024-10-08 16:15 UTC, jiceatscion commented on draft-dekater-scion-dataplane.md
> +- `Sequence Number` (64 bits) indicates the position of the frame within a stream. Consecutive frames can be used to reassemble IP packets split among multiple frames.
I would go as far as embedding a design doc in the draft.

I would add the following to the `Sequence number` paragraph:
"Frames can, rarely, be delayed or lost. When a frame other than the next expected one is received, any previously received frames, pertaining to a yet incomplete IP packet, are discarded. Subsequent frames are discarded until one carries the beginning of an IP packet. Late frames (with a sequence number older than any non-discarded ones) are discarded as they necessarily belong to an already discarded IP packet."

2024-10-08 16:18 UTC, jiceatscion commented on draft-dekater-scion-dataplane.md
> +- `Index` (16 bits) is the byte offset of the first beginning of an IP packet within the payload. If no IP packet starts in the payload, e.g. if the frame contains only a trailing part of an IP packe
Yeah, that works too :-)

2024-10-09 14:05 UTC, nicorusti commented on draft-dekater-scion-dataplane.md
> +- `Sequence Number` (64 bits) indicates the position of the frame within a stream. Consecutive frames can be used to reassemble IP packets split among multiple frames.
Could we say more generally that the SIG should take care of packer reordering but that further details are left to implementors?

2024-10-09 14:27 UTC, nicorusti commented on draft-dekater-scion-dataplane.md
> +TODO: @oncilla @shitz could you say something about why this framing and not existing protocol? Is it because of MTU?
@oncilla @shitz do you have some background on why SIGs use their own framing protocol rather than any of the existing ones?
@oncilla I remember you mentioned at some point that no other protocol fulfilled the needs. Which needs? Is it because SIG framing can fragment an IP packet in multiple frames, without incurring into MTU problems?

2024-10-09 14:41 UTC, shitz commented on draft-dekater-scion-dataplane.md
> +TODO: @oncilla @shitz could you say something about why this framing and not existing protocol? Is it because of MTU?
I cannot remember what lead to the decision to create a custom framing protocol. There are certainly some requirements/properties that we wanted, e.g., non-reliable transport, independence of SCION MTU (because that can increase and decrease over time), fast detection of packet loss and subsequent recovery of decapsulation for packets that weren't lost, support for multiple streams within a framing session such that the streams can be distributed to separate cores.
I'm not sure if there was an investigation whether an existing framing protocol would have all of these properties or if it simply wasn't done, but at least there is some justification why the framing protocol is the way it is.

2024-10-10 15:57 UTC, jiceatscion commented on draft-dekater-scion-dataplane.md
> +A pair of SIGs establishes a SIG tunneling session. TODO: how?.  Within each session there may be multiple streams which is useful to distinguish between traffic sent by different SIG instances. For
My notes, before I start forgetting... the code is tough read:

* Sessions are unidirectional and initiated by senders upon discovering other gateways.
* Gateway are discovered only in remote IAs that are statically configured.
* The initiator gateway allocates one session per (receiverGateway, sessionPolicy) pair.
* All initiated sessions have a unique ID that is simply incremented from 0. The numbering is re-done every time the set of remote gateways changes. To keep the numbers ~stable, the sessions are ordered by (policy>IA). I haven't searched for the effects of session re-IDing.
* Since there are only 256 session IDs they are not necessarily unique, but they are unique within a given (initiator, receiver) pair, as long as there aren't 256+ session policies for a given remote IA.
* From a given initiator to a given receiver, the traffic of all endpoint pairs is multiplexed on the same session.
* All paths between two gateways can be used by any given one session.
* All paths, regardless of session get their own sender, queue, and ~random streamID.
* The receiver side just follows these. It will accept any connection (I haven't checked if sending IAs are checked against the static config.
* The receiver side has one worker for each incoming session, that is each (sender gateway, sessionID) pair. It is created on the fly as needed.
* Each worker keeps a different reassembly queue for each streamID (but streams share the same worker task, unlike on the sending side).

Conclusion, regarding sessionID and StreamID. Each (sessionID, streamID) pair gets its own re-assembly queue. The pairs are ~unique within the context where it matters (one gateway->gateway pair) by virtue of sessionID being unique, but only approximately: there can be streamID collisions with P=O(10^-9) as long as there aren't too many paths. It might hurt a bit when that happens.

2024-10-11 13:18 UTC, shitz requested changes

2024-10-11 13:18 UTC, shitz commented on draft-dekater-scion-dataplane.md
> +- `Sequence Number` (64 bits) indicates the position of the frame within a stream. Consecutive frames can be used to reassemble IP packets split among multiple frames.
This is completely implementation specific. Just because the open-source implementation has a reassembly window of a single fragment doesn't mean that you could easily have implementations that for exmaple allow for up to N out-of-order fragments because they keep them in a buffer and reassemble the packet once all fragments have been received. I would not put this in the draft and state that it's implementation specific. This is even a completely local decision for each SIG.

2024-10-11 13:18 UTC, shitz commented on draft-dekater-scion-dataplane.md
> +- how is the session established and torn down?
> how is the session established and torn down?
As stated above, there is no real session establishment. The sender chooses session ID, stream ID unilateraly. 

> How is the stream ID set randomly? Is it negotiated? Is it associated with a session? Does it have to be unique within a session? Is it unidirectional?

1. Chosen unilaterally by the sender however it sees fit
2. no
3. (session id, stream id) tuple needs to be unique
4. yes
5. yes

2024-10-15 08:15 UTC, nicorusti commented on draft-dekater-scion-dataplane.md
> +IP packets are encapsulated over SCION/UDP into SIG frames. Whilst in principle, a pair of SIGs may use other tunneling protocols, existing deployments use SIG framing as described here. This is to p
```suggestion
IP packets are encapsulated over SCION/UDP into SIG frames. Whilst in principle, a pair of SIGs may use other tunneling protocols, existing deployments use SIG framing as described here. This is to provide independence from the underlying SCION path MTU which can increase and decrease over time, to provide fast detection of packet loss and subsequent recovery of decapsulation for packets that weren't lost, and support for multiple streams within a framing session such that the streams can be distributed to separate cores.
```

2024-10-15 08:15 UTC, nicorusti commented on draft-dekater-scion-dataplane.md
> +A pair of SIGs establishes a SIG tunneling session which are is unidirectionally established by the sender. Whether a session is mapped to a single path or not is an implementation decision.
```suggestion
A source SIG unidirectionally establishes a SIG tunneling session with a destination SIG. A session may be mapped to one or multiple SCION paths, depending on implementors.
```

2024-10-15 08:15 UTC, nicorusti commented on draft-dekater-scion-dataplane.md
> +Streams can be used within a session to distinguish between different packet flows. A single stream has a single reassembly queue and should be processed by a single core. Packets in a stream should
```suggestion
Streams can be used within a session to distinguish between different packet flows. A single stream has a single reassembly queue and SHOULD be processed by a single core. Packets in a stream SHOULD NOT be distributed over multiple SCION paths to avoid reordering and therefore lower performance.
```

2024-10-15 08:15 UTC, nicorusti commented on draft-dekater-scion-dataplane.md
> +TODO: how are the sessions established? Is a session mapped to a single path?
THanks a lot, @knmeynell added a derivative of this text to the draft

2024-10-15 08:33 UTC, jiceatscion commented
For simplicity of the process, I accepted suggestions. I think this is good enough to merge (even if we leave it at that). We can do another pass after that.

2024-10-15 08:34 UTC, nicorusti approved these changes
I left a couple of comments, I think after this this is good to merge  (sorry, one more suggestion for you @jiceatscion 🥲 )

2024-10-15 08:34 UTC, nicorusti commented on draft-dekater-scion-dataplane.md
> +- `Sequence Number` (64 bits) indicates the position of the frame within a stream. Consecutive frames can be used to reassemble IP packets split among multiple frames. In the rare event that a frame
```suggestion
- `Sequence Number` (64 bits) indicates the position of the frame within a stream. Consecutive frames are used to reassemble IP packets split among multiple frames.

SIGs MAY reorder received frames within a stream. Choice of frame reassembly window is left to implementations.
```

2024-10-15 08:48 UTC, jiceatscion commented
Accepted. In the next pass I will mention that the egress SIG is free to buffer packets for re-ordering, or discard; as a unilateral decision.

2024-10-15 08:49 UTC, merged